pyvista/pytest-pyvista

.github/workflows/ci_cd.yml
.gitignore
pyproject.toml
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

Closes #16 
This PR now requires a cache_dir be set within `VeriryImageClass`.  The default is set according to the configuration (`setup.cfg` or `pyproject.toml`) or command line in the fixture.
The existing tests were flawed in that they never tested against an image cache and would always pass.  An image is now dynamically generated for the temporary cache.
Feedback on naming of the public options is specifically requested.

Better default cache dir and config options

---

pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

The current class attributes mean that the values leak out of tests into other tests.  Using instance attributes fixes this problem as the `VerifyImageCache` object is intended to be initialized in a fixture for each test.
Additional tests were added for high variance tests, but not the OS specific skips.

Use instance attributes for high variance and skipping based on os

---

.github/workflows/ci_cd.yml
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

`pyvista` tests include plotting with vtk version 8 but do not support image caching.  However, it is still useful to test that the tests run on these versions without error.  This PR adds the option to raise an error for vtk8 (default) or skip image cache testing.
This would fix vtk version related failures for https://github.com/pyvista/pyvista/pull/3748

Option for skipping on vtk8

---

pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

Fix reset_image_cache

---

.github/workflows/ci_cd.yml
pyproject.toml

Having PyVista as a hard dependency provides a headache for installing targeted versions of both PyVista and VTK.
PyVista has `vtk` listed as a requirement, and I don't think we want to remove that. We are beginning to use new `vtk_osmesa` wheels for CI and we need to be able to have `pytest-pyvista` in `requirements.txt` without a `--no-deps` option. Problem is, this pulls/checks pyvista and thus pulls `vtk`. This provides an issue if using the `vtk_osmesa` (or other build variant) wheel and will also mess with the pyvista install if the version isn't right.
IMO, if you're using `pytest-pyvista`, it's obvious you'll need `pyvista` installed and thus removing it as a dependency here shouldn't be too confusing.
After all, this module is not meant to be directly interfaced with by users but …

Remove PyVista from dependencies

---

.github/workflows/ci_cd.yml
README.rst
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

This PR removes vtk8 handling.
This is related to https://github.com/pyvista/pyvista/pull/4018.

Remove vtk8 handling

---

.github/workflows/ci_cd.yml
.pre-commit-config.yaml
README.rst
pyproject.toml

CI is starting to fail due to conflicts with python 3.7. PyVista no longer supports this version, so we should drop here too.

Fix CI; Remove python 3.7; remove flake8-isort

---

pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

As the title.
It resets the cache if the image comparison fails.
It does not raise an error.
Working on the tests...
Close #83

Reset cache only if error

---

README.rst

This pull-request updates the `README.rst` with simple instructions to the user community on how to install `pytest-pyvista` using `conda` or `mamba` from the newly hatched package on [conda-forge](https://anaconda.org/conda-forge/pytest-pyvista).

Update README with conda/mamba install

---

.github/workflows/ci_cd.yml
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

Adding custom error class

---

README.rst
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

This pull-request adds the convenience of specifying the `generated_image_dir` as a `pytest` INI configuration option, complimenting its associated CLI option.
This is akin to the support provided for the `image_cache_dir` option.

Add generated_image_dir ini configuration

---

.github/workflows/ci_cd.yml

Add Python3.12 support at the latest `vtk` version.

Add Python3.12 support at the latest `vtk` version

---

.github/workflows/ci_cd.yml
README.rst
pyproject.toml

ref https://github.com/pyvista/pyvista/pull/6701

Drop Python 3.8 support which is EOL in 07 Oct 2024

---

.github/workflows/ci_cd.yml
pyproject.toml

ubuntu-20.04 is unsupported.
https://github.com/actions/runner-images/issues/11101
Further fixes are adding python 3.13 testing support and updating to use --group installation requirements from pyvista.

Modernize testing versions and installation in CI

---

pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

The docs state no images are saved unless this option is set:
https://github.com/pyvista/pytest-pyvista/blob/10952115b004451f5afa8382ff6dd3ccb022d103/pytest_pyvista/pytest_pyvista.py#L100-L102
Though, this is for `VerifyImageCache.__init__` (not sure if this class is used this way without the fixture / pytest options). The README is less clear about this:
https://github.com/pyvista/pytest-pyvista/blob/10952115b004451f5afa8382ff6dd3ccb022d103/README.rst?plain=1#L107-L108
But it seems to me that the intention of this option was for it to originally be optional. When this option was initially added in https://github.com/pyvista/pytest-pyvista/pull/22, it was not enabled by default
But, when the `pytest.ini` option was added in https://github.com/pyvista/pytest-pyvista/pull/96, this added a …

Set default generated image dir to `None`

---

README.rst
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

New option to save any tests where a warning or error was generated. 
Currently, if a test fails and we want to review the results, we have to manually search for the generated image in the `generated_image_dir` as well as manually search for the cached image in the `cache_image_dir`. This can be challenging with 500+ images in the pyvista repo. With this PR, these results are captured and copied into a separate easy-to-review location in `failed_image_dir`. This is similar to how the documentation image tests currently work for pyvista.
~This PR builds upon code from #169~

Add `failed_image_dir` option

---

.github/workflows/ci_cd.yml
README.rst
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

Follow-up to https://github.com/pyvista/pytest-pyvista/pull/92. Instead of simply renaming the argument, this PR also changes the default behavior so that an error is now raised by default if a generated image has no use.
I think this also resolves #36. The name `--allow_unused_generated` doesn't conflict with `--add_missing_images`, since enabling `--add_missing_images` is considered to be a usage of the images. This is documented in the README.

Add `allow_unused_generated` option as a replacement for `fail_extra_image_cache`

---

.github/workflows/ci_cd.yml
README.rst
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

The `verify_image_cache` fixture is sometimes used unnecessarily when no calls to `plot` or show` are made and hence there is nothing to verify. This PR adds an option to check for this and will fail the test's teardown.

Add `allow_useless_fixture` CLI option

---

.github/workflows/ci_cd.yml
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

Use `--branch` to report partial misses and add tests for branches without coverage.

Improve test coverage

---

.github/workflows/ci_cd.yml
README.rst
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

New CLI option to fix #28 and https://github.com/pyvista/pyvista/issues/7582
This works by storing test results info into ~a global dict~ global sets. The ~dict~ set is populated each time `verify_image_cache` is called, OR whenever a test is skipped during test setup or test execution. This should handle cases where tests are skipped based on OS version or VTK version and not inadvertently fail.

Add `disallow_unused_cache` option

---

.github/workflows/ci_cd.yml
pyproject.toml

Release step failed in:
https://github.com/pyvista/pytest-pyvista/actions/runs/16119988259/job/45483046060
```
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
- flit_core >=3.2,<4
* Getting build dependencies for sdist...
Unexpected names under [project]: python_requires
* Building sdist...
Unexpected names under [project]: python_requires
* Building wheel from sdist
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
- flit_core >=3.2,<4
* Getting build dependencies for wheel...
Unexpected names under [project]: python_requires
* Building wheel...
Unexpected names under [project]: python_requires
Successfully built pytest_pyvista-0.2.0.tar.gz and pytest_pyvista-0.2.0-py2.py3-none-any.whl
Checking …
```

Fix license field

---

pyproject.toml
tests/test_pyvista.py

According to `pytest` [documentation](https://docs.pytest.org/en/latest/reference/reference.html#std-fixture-testdir), the `testdir` fixture is to be replaced with the more recent `pytester` one.
In addition to that, `result.stdout.fnmatch_lines("*[Pp]assed*")` calls are replaced by `result.assert_outcomes(passed=1)` to explicitly count the number of test status.

Use pytester instead testdir

---

pyproject.toml
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

The `verify_image_cache` object is not called when a `before_close_callback` is already injected in `Plotter.show()`.
```python
import pyvista as pv
pv.OFF_SCREEN = True
def test_imcache(verify_image_cache, mocker):
sphere = pv.Sphere()
plotter = pv.Plotter()
plotter.add_mesh(sphere, color="red")
plotter.show(before_close_callback=(m := mocker.MagicMock()))
m.assert_called_once_with(plotter)
```
```python
E               Failed: Fixture `verify_image_cache` is used but no images were generated.
E               Did you forget to call `show` or `plot`, or set `verify_image_cache.allow_useless_fixture=True`?.
```
This PR fixes it by fully wrapping the call to `Plotter.show`, injecting the `verify_image_cache` object on-the-fly after the user callback.
It induces that …

Fix callback

---

README.rst
pyproject.toml
pytest_pyvista/pytest_pyvista.py
tests/test_pyvista.py

Allow customizing info saved in image filenames when using `--generate_subdirs`. See https://github.com/pyvista/pytest-pyvista/pull/211#pullrequestreview-3183786750 for details.
Adds a new dataclass with the option to customize it using `verify_image_cache.env_info`.

Allow customizing env info

---

README.rst
pytest_pyvista/doc_mode.py
pytest_pyvista/pytest_pyvista.py
tests/test_doc_mode.py

The doc mode options should all be prefixed with `doc` to distinguish them from regular unit test options. This will allow specifying both options in the config file:
``` toml
[tool.pytest.ini_options]
image_format = 'png'
doc_image_format = 'jpg'
```

Allow separate image format for doc mode

---

.github/workflows/ci_cd.yml
README.rst
pyproject.toml

Python 3.9 reaches EOL on October 30. I propose dropping support for it. `pyvista` has already done so downstream.
My main motivation is that I'm seeing seg faults with #227 for vtk 9.1 with python 3.9, and so some tests are skipped, but coverage is only reported for 3.9, and hence missing coverage is being reported even though it is covered by later versions.
I don't think these seg faults are necessarily inherent to vtk 9.1, and may be an issue with our CI (tests that were previously passing are now failing as additional tests were added), but instead of trying to isolate and fix this I think it may be better to drop support completely based on python 3.9 EOL.

Drop support for Python 3.9 and VTK 9.1
